### ISSUE TITLE
add general method set_status()

### ISSUE THREAD

**Issue by borisdaeppen** [borisdaeppen/VM-JiffyBox#30]
`start()` and `stop()` are just special cases of the status-command. We should add a general method `set_status()` which would then be used like this
```perl
$vm->set_status('START') # or SHUTDOWN, PULLPLUG, FREEZE, THAW
```
Like this the user can use the whole variety of commands from the API.

(or we add separate methods for each process... like `freeze()`)

**Comment by reneeb** [comment]
As of #46 there is a _status_action and start, stop, freeze, thaw just use that function. This way, the user doesn't need to know the status names. And when JiffyBox changes its API, the user doesn't have to update the code...

**Comment by borisdaeppen** [comment]
Thank you a lot for your commits, merged
